# First Trial with Austrian Data {#sec-annex90}


```{r}
#| label: setup
#| include: false

base::source(file = "R/helper.R")
```


## Shares of pre-tax national income of top 1%

```{r}
sptinc_data_at <- wid::download_wid(
    indicators = "sptinc", # Shares of pre-tax national income
    areas = "AT", # In Austria
    years = 1995:2022, # Time period: 1995:2022
    perc = "p99p100" # Top 1% only
)
# knitr::kable(data) # Pretty display of the data.frame

sptinc_data_at |> 
    ggplot2::ggplot(
        ggplot2::aes(
            x = year,
            y = value)
    ) +
    ggplot2::geom_line()
```
## Shares of net personal wealth top 1% only

```{r}
shweal_data_at <- wid::download_wid(
    indicators = "shweal", # Shares of net personal wealth
    areas = "AT", # In Austria
    years = 1995:2022, # Time period: 1995:2022 (default: all)
    perc = "p99p100" # Top 1% only
)

# knitr::kable(data) # Pretty display of the data.frame

shweal_data_at |> 
    ggplot2::ggplot(
        ggplot2::aes(
            x = year,
            y = value)
    ) +
    ggplot2::geom_line()
```
## Shares of pre-taxnational income of bottom 50%, top 10% and top 1%

### Income inequality, Austria, 1980-2022 (iframe)

<iframe width="800" height="400" src="https://wid.world/share/#1/countrytimeseries/sptinc_p99p100_z;sptinc_p0p50_z;sptinc_p90p100_z/AT/2015/eu/k/p/yearly/s/true/-15/40/curve/true/1980/2022"></iframe>

### Income inequality, Austria, 1980-2022 (own calculation)


```{r}
income_austria <- wid::download_wid(
    indicators = "sptinc", # Shares of pre-tax national income
    areas = "AT", # Austria
    perc = c("p0p50", "p90p100", "p99p100") # Bottom 50%, top 10% and top 1%
)

ggplot2::ggplot(income_austria, 
    ggplot2::aes(x = year, y = value, color = percentile)) +
    ggplot2::geom_line() + 
    ggplot2::geom_point() +
    ggplot2::ylab("share of income") +
    ggplot2::scale_color_discrete(
        labels = c("p0p50" = "bottom 50%", "p90p100" = "top 10%", "p99p100" = "top 1%")
    ) + 
    ggplot2::ggtitle("Pre-tax national income inequality in Austria")

```

